import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  DynamicContextProvider,
  SolanaWalletConnectors,
  EthereumWalletConnectors,
  FlowWalletConnectors,
  CosmosWalletConnectors,
  BloctoEvmWalletConnectors,
  AlgorandWalletConnectors,
  StarknetWalletConnectors,
  MagicWalletConnectors,
} from "../lib/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        theme={"dark"}
        settings={{
          environmentId: "56f64688-b5b5-457a-a1cc-1ad32ab9336c",
          walletConnectors: [
            EthereumWalletConnectors,
            FlowWalletConnectors,
            CosmosWalletConnectors,
            BloctoEvmWalletConnectors,
            AlgorandWalletConnectors,
            StarknetWalletConnectors,
            MagicWalletConnectors,
            SolanaWalletConnectors,
          ],
        }}
      >
        <body className={inter.className}>{children}</body>
      </DynamicContextProvider>
    </html>
  );
}
